/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	cloudclustersv1 "github.com/sean/tasktests/pkg/apis/cloudclusters/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaskTests implements TaskTestInterface
type FakeTaskTests struct {
	Fake *FakeCloudclustersV1
	ns   string
}

var tasktestsResource = schema.GroupVersionResource{Group: "cloudclusters.io", Version: "v1", Resource: "tasktests"}

var tasktestsKind = schema.GroupVersionKind{Group: "cloudclusters.io", Version: "v1", Kind: "TaskTest"}

// Get takes name of the taskTest, and returns the corresponding taskTest object, and an error if there is any.
func (c *FakeTaskTests) Get(name string, options v1.GetOptions) (result *cloudclustersv1.TaskTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tasktestsResource, c.ns, name), &cloudclustersv1.TaskTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cloudclustersv1.TaskTest), err
}

// List takes label and field selectors, and returns the list of TaskTests that match those selectors.
func (c *FakeTaskTests) List(opts v1.ListOptions) (result *cloudclustersv1.TaskTestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tasktestsResource, tasktestsKind, c.ns, opts), &cloudclustersv1.TaskTestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &cloudclustersv1.TaskTestList{ListMeta: obj.(*cloudclustersv1.TaskTestList).ListMeta}
	for _, item := range obj.(*cloudclustersv1.TaskTestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taskTests.
func (c *FakeTaskTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tasktestsResource, c.ns, opts))

}

// Create takes the representation of a taskTest and creates it.  Returns the server's representation of the taskTest, and an error, if there is any.
func (c *FakeTaskTests) Create(taskTest *cloudclustersv1.TaskTest) (result *cloudclustersv1.TaskTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tasktestsResource, c.ns, taskTest), &cloudclustersv1.TaskTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cloudclustersv1.TaskTest), err
}

// Update takes the representation of a taskTest and updates it. Returns the server's representation of the taskTest, and an error, if there is any.
func (c *FakeTaskTests) Update(taskTest *cloudclustersv1.TaskTest) (result *cloudclustersv1.TaskTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tasktestsResource, c.ns, taskTest), &cloudclustersv1.TaskTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cloudclustersv1.TaskTest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTaskTests) UpdateStatus(taskTest *cloudclustersv1.TaskTest) (*cloudclustersv1.TaskTest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tasktestsResource, "status", c.ns, taskTest), &cloudclustersv1.TaskTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cloudclustersv1.TaskTest), err
}

// Delete takes name of the taskTest and deletes it. Returns an error if one occurs.
func (c *FakeTaskTests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tasktestsResource, c.ns, name), &cloudclustersv1.TaskTest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaskTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tasktestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &cloudclustersv1.TaskTestList{})
	return err
}

// Patch applies the patch and returns the patched taskTest.
func (c *FakeTaskTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *cloudclustersv1.TaskTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tasktestsResource, c.ns, name, data, subresources...), &cloudclustersv1.TaskTest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*cloudclustersv1.TaskTest), err
}
